spring.application.name=service-registery

# Server port for Eureka
server.port=${SERVER_PORT:8761}

# Eureka server configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disable self-preservation (optional, for dev/testing)
eureka.server.enable-self-preservation=false

# Eureka dashboard hostname
eureka.instance.hostname=localhost

# Logging (optional)
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF
