spring.application.name=order-service

#app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000}
#app.cors.allowed-origins=http://localhost:3000,http://192.168.3.44:3000
 
 
# Server
server.port=${SERVER_PORT:8082}


# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/order_service
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# MySQL driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

razorpay.key.id=${key_id}
razorpay.key.secret=${key_secret}

eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/order-service/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
